###

POST http://localhost:3333/api/login HTTP/1.1
Content-Type: Application/json

{
   "identifier": "0123456789",
   "password": "123456"
}

###
POST http://localhost:3333/api/register HTTP/1.1
Content-Type: Application/json

{
   "firstName": "User",
   "lastName": "one",
   "email": "user1@mail.com",
   "phone": "0123456789",
   "password": "123456",
   "password_confirmation": "123456"
}
